export const PokemonTypes = [
    { value: "fire", label: "Fogo" },
    { value: "water", label: "Água" },
    { value: "grass", label: "Planta" },
    { value: "electric", label: "Elétrico" },
    { value: "ice", label: "Gelo" },
    { value: "fighting", label: "Lutador" },
    { value: "poison", label: "Venenoso" },
    { value: "ground", label: "Terrestre" },
    { value: "flying", label: "Voador" },
    { value: "psychic", label: "Psíquico" },
    { value: "bug", label: "Inseto" },
    { value: "rock", label: "Pedra" },
    { value: "ghost", label: "Fantasma" },
    { value: "dragon", label: "Dragão" },
    { value: "dark", label: "Sombrio" },
    { value: "steel", label: "Aço" },
    { value: "fairy", label: "Fada" },
];
